name: automatic deployment
on: 
  push:
    branches: [main]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Uploading files.
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.4
      with:
        host: ${{ secrets.BGASTUDIO_SERVER }}
        port: 22
        username: ${{ secrets.BGASTUDIO_USERNAME }}
        password: ${{ secrets.BGASTUDIO_PASSWORD }}
        localPath: 'C/Users/jonat/OneDrive/Documents/Projects/BGAProjects/ReversiTutorial/*'
        remotePath: '/reversijgptutorial'